# -*- coding: utf-8 -*-
"""Hungry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18zjAJdMjXc5sEe77cEmQasJlXhZwOcO6
"""

print("I am Hungry")